In [1]:
#support vector machine (SVM) Hands on - SVM-Regresssion - dept-investment-profit pred.
#import libraries
import pandas as pd

In [2]:
#reading the data file
dataset=pd.read_csv("50_Startups.csv")

In [93]:
#just to display dataset
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0
5,131876.90,99814.71,362861.36,156991.12,0,1
6,134615.46,147198.87,127716.82,156122.51,0,0
7,130298.13,145530.06,323876.68,155752.60,1,0
8,120542.52,148718.95,311613.29,152211.77,0,1
9,123334.88,108679.17,304981.62,149759.96,0,0
10,101913.08,110594.11,229160.95,146121.95,1,0
11,100671.96,91790.61,249744.55,144259.40,0,0
12,93863.75,127320.38,249839.44,141585.52,1,0
13,91992.39,135495.07,252664.93,134307.35,0,0
14,119943.24,156547.42,256512.92,132602.65,1,0
15,114523.61,122616.84,261776.23,129917.04,0,1
16,78013.11,121597.55,264346.06,126992.93,0,0
17,94657.16,145077.58,282574.31,125370.37,0,1
18,91749.16,114175.79,294919.57,124266.90,1,0
19,86419.70,153514.11,0.00,122776.86,0,1
20,76253.86,113867.30,298664.47,118474.03,0,0
21,78389.47,153773.43,299737.29,111313.02,0,1
22,73994.56,122782.75,303319.26,110352.25,1,0
23,67532.53,105751.03,304768.73,108733.99,1,0
24,77044.01,99281.34,140574.81,108552.04,0,1
25,64664.71,139553.16,137962.62,107404.34,0,0
26,75328.87,144135.98,134050.07,105733.54,1,0
27,72107.60,127864.55,353183.81,105008.31,0,1
28,66051.52,182645.56,118148.20,103282.38,1,0
29,65605.48,153032.06,107138.38,101004.64,0,1
30,61994.48,115641.28,91131.24,99937.59,1,0
31,61136.38,152701.92,88218.23,97483.56,0,1
32,63408.86,129219.61,46085.25,97427.84,0,0
33,55493.95,103057.49,214634.81,96778.92,1,0
34,46426.07,157693.92,210797.67,96712.80,0,0
35,46014.02,85047.44,205517.64,96479.51,0,1
36,28663.76,127056.21,201126.82,90708.19,1,0
37,44069.95,51283.14,197029.42,89949.14,0,0
38,20229.59,65947.93,185265.10,81229.06,0,1
39,38558.51,82982.09,174999.30,81005.76,0,0
40,28754.33,118546.05,172795.67,78239.91,0,0
41,27892.92,84710.77,164470.71,77798.83,1,0
42,23640.93,96189.63,148001.11,71498.49,0,0
43,15505.73,127382.30,35534.17,69758.98,0,1
44,22177.74,154806.14,28334.72,65200.33,0,0
45,1000.23,124153.04,1903.93,64926.08,0,1
46,1315.46,115816.21,297114.46,49490.75,1,0
47,0.00,135426.92,0.00,42559.73,0,0
48,542.05,51743.15,0.00,35673.41,0,1
49,0.00,116983.80,45173.06,14681.40,0,0

In [ ]:
#understand two set of variables X_train and x_train (case sensitives - holding two diff sets)

In [4]:
#categorical data is present - nominal (by name - state name)
#expanding columns - as machine understanding - one hot encoding
dataset=pd.get_dummies(dataset)

In [5]:
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_California,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,0,1
1,162597.70,151377.59,443898.53,191792.06,1,0,0
2,153441.51,101145.55,407934.54,191050.39,0,1,0
3,144372.41,118671.85,383199.62,182901.99,0,0,1
4,142107.34,91391.77,366168.42,166187.94,0,1,0
5,131876.90,99814.71,362861.36,156991.12,0,0,1
6,134615.46,147198.87,127716.82,156122.51,1,0,0
7,130298.13,145530.06,323876.68,155752.60,0,1,0
8,120542.52,148718.95,311613.29,152211.77,0,0,1
9,123334.88,108679.17,304981.62,149759.96,1,0,0
10,101913.08,110594.11,229160.95,146121.95,0,1,0
11,100671.96,91790.61,249744.55,144259.40,1,0,0
12,93863.75,127320.38,249839.44,141585.52,0,1,0
13,91992.39,135495.07,252664.93,134307.35,1,0,0
14,119943.24,156547.42,256512.92,132602.65,0,1,0
15,114523.61,122616.84,261776.23,129917.04,0,0,1
16,78013.11,121597.55,264346.06,126992.93,1,0,0
17,94657.16,145077.58,282574.31,125370.37,0,0,1
18,91749.16,114175.79,294919.57,124266.90,0,1,0
19,86419.70,153514.11,0.00,122776.86,0,0,1
20,76253.86,113867.30,298664.47,118474.03,1,0,0
21,78389.47,153773.43,299737.29,111313.02,0,0,1
22,73994.56,122782.75,303319.26,110352.25,0,1,0
23,67532.53,105751.03,304768.73,108733.99,0,1,0
24,77044.01,99281.34,140574.81,108552.04,0,0,1
25,64664.71,139553.16,137962.62,107404.34,1,0,0
26,75328.87,144135.98,134050.07,105733.54,0,1,0
27,72107.60,127864.55,353183.81,105008.31,0,0,1
28,66051.52,182645.56,118148.20,103282.38,0,1,0
29,65605.48,153032.06,107138.38,101004.64,0,0,1
30,61994.48,115641.28,91131.24,99937.59,0,1,0
31,61136.38,152701.92,88218.23,97483.56,0,0,1
32,63408.86,129219.61,46085.25,97427.84,1,0,0
33,55493.95,103057.49,214634.81,96778.92,0,1,0
34,46426.07,157693.92,210797.67,96712.80,1,0,0
35,46014.02,85047.44,205517.64,96479.51,0,0,1
36,28663.76,127056.21,201126.82,90708.19,0,1,0
37,44069.95,51283.14,197029.42,89949.14,1,0,0
38,20229.59,65947.93,185265.10,81229.06,0,0,1
39,38558.51,82982.09,174999.30,81005.76,1,0,0
40,28754.33,118546.05,172795.67,78239.91,1,0,0
41,27892.92,84710.77,164470.71,77798.83,0,1,0
42,23640.93,96189.63,148001.11,71498.49,1,0,0
43,15505.73,127382.30,35534.17,69758.98,0,0,1
44,22177.74,154806.14,28334.72,65200.33,1,0,0
45,1000.23,124153.04,1903.93,64926.08,0,0,1
46,1315.46,115816.21,297114.46,49490.75,0,1,0
47,0.00,135426.92,0.00,42559.73,1,0,0
48,542.05,51743.15,0.00,35673.41,0,0,1
49,0.00,116983.80,45173.06,14681.40,1,0,0

In [6]:
#droping first column - to avoid repetition
dataset1=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [7]:
dataset1

,R&D Spend,Administration,Marketing Spend,Profit,State_California,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,0,1
1,162597.70,151377.59,443898.53,191792.06,1,0,0
2,153441.51,101145.55,407934.54,191050.39,0,1,0
3,144372.41,118671.85,383199.62,182901.99,0,0,1
4,142107.34,91391.77,366168.42,166187.94,0,1,0
5,131876.90,99814.71,362861.36,156991.12,0,0,1
6,134615.46,147198.87,127716.82,156122.51,1,0,0
7,130298.13,145530.06,323876.68,155752.60,0,1,0
8,120542.52,148718.95,311613.29,152211.77,0,0,1
9,123334.88,108679.17,304981.62,149759.96,1,0,0
10,101913.08,110594.11,229160.95,146121.95,0,1,0
11,100671.96,91790.61,249744.55,144259.40,1,0,0
12,93863.75,127320.38,249839.44,141585.52,0,1,0
13,91992.39,135495.07,252664.93,134307.35,1,0,0
14,119943.24,156547.42,256512.92,132602.65,0,1,0
15,114523.61,122616.84,261776.23,129917.04,0,0,1
16,78013.11,121597.55,264346.06,126992.93,1,0,0
17,94657.16,145077.58,282574.31,125370.37,0,0,1
18,91749.16,114175.79,294919.57,124266.90,0,1,0
19,86419.70,153514.11,0.00,122776.86,0,0,1
20,76253.86,113867.30,298664.47,118474.03,1,0,0
21,78389.47,153773.43,299737.29,111313.02,0,0,1
22,73994.56,122782.75,303319.26,110352.25,0,1,0
23,67532.53,105751.03,304768.73,108733.99,0,1,0
24,77044.01,99281.34,140574.81,108552.04,0,0,1
25,64664.71,139553.16,137962.62,107404.34,1,0,0
26,75328.87,144135.98,134050.07,105733.54,0,1,0
27,72107.60,127864.55,353183.81,105008.31,0,0,1
28,66051.52,182645.56,118148.20,103282.38,0,1,0
29,65605.48,153032.06,107138.38,101004.64,0,0,1
30,61994.48,115641.28,91131.24,99937.59,0,1,0
31,61136.38,152701.92,88218.23,97483.56,0,0,1
32,63408.86,129219.61,46085.25,97427.84,1,0,0
33,55493.95,103057.49,214634.81,96778.92,0,1,0
34,46426.07,157693.92,210797.67,96712.80,1,0,0
35,46014.02,85047.44,205517.64,96479.51,0,0,1
36,28663.76,127056.21,201126.82,90708.19,0,1,0
37,44069.95,51283.14,197029.42,89949.14,1,0,0
38,20229.59,65947.93,185265.10,81229.06,0,0,1
39,38558.51,82982.09,174999.30,81005.76,1,0,0
40,28754.33,118546.05,172795.67,78239.91,1,0,0
41,27892.92,84710.77,164470.71,77798.83,0,1,0
42,23640.93,96189.63,148001.11,71498.49,1,0,0
43,15505.73,127382.30,35534.17,69758.98,0,0,1
44,22177.74,154806.14,28334.72,65200.33,1,0,0
45,1000.23,124153.04,1903.93,64926.08,0,0,1
46,1315.46,115816.21,297114.46,49490.75,0,1,0
47,0.00,135426.92,0.00,42559.73,1,0,0
48,542.05,51743.15,0.00,35673.41,0,0,1
49,0.00,116983.80,45173.06,14681.40,1,0,0

In [11]:
#above code not dropping first column as version change, so modified as follows
import pandas as pd
dataset=pd.read_csv("50_Startups.csv")
dataset
# Convert categorical variables into dummy/indicator variables and drop the first category.
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [12]:
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0
5,131876.90,99814.71,362861.36,156991.12,0,1
6,134615.46,147198.87,127716.82,156122.51,0,0
7,130298.13,145530.06,323876.68,155752.60,1,0
8,120542.52,148718.95,311613.29,152211.77,0,1
9,123334.88,108679.17,304981.62,149759.96,0,0
10,101913.08,110594.11,229160.95,146121.95,1,0
11,100671.96,91790.61,249744.55,144259.40,0,0
12,93863.75,127320.38,249839.44,141585.52,1,0
13,91992.39,135495.07,252664.93,134307.35,0,0
14,119943.24,156547.42,256512.92,132602.65,1,0
15,114523.61,122616.84,261776.23,129917.04,0,1
16,78013.11,121597.55,264346.06,126992.93,0,0
17,94657.16,145077.58,282574.31,125370.37,0,1
18,91749.16,114175.79,294919.57,124266.90,1,0
19,86419.70,153514.11,0.00,122776.86,0,1
20,76253.86,113867.30,298664.47,118474.03,0,0
21,78389.47,153773.43,299737.29,111313.02,0,1
22,73994.56,122782.75,303319.26,110352.25,1,0
23,67532.53,105751.03,304768.73,108733.99,1,0
24,77044.01,99281.34,140574.81,108552.04,0,1
25,64664.71,139553.16,137962.62,107404.34,0,0
26,75328.87,144135.98,134050.07,105733.54,1,0
27,72107.60,127864.55,353183.81,105008.31,0,1
28,66051.52,182645.56,118148.20,103282.38,1,0
29,65605.48,153032.06,107138.38,101004.64,0,1
30,61994.48,115641.28,91131.24,99937.59,1,0
31,61136.38,152701.92,88218.23,97483.56,0,1
32,63408.86,129219.61,46085.25,97427.84,0,0
33,55493.95,103057.49,214634.81,96778.92,1,0
34,46426.07,157693.92,210797.67,96712.80,0,0
35,46014.02,85047.44,205517.64,96479.51,0,1
36,28663.76,127056.21,201126.82,90708.19,1,0
37,44069.95,51283.14,197029.42,89949.14,0,0
38,20229.59,65947.93,185265.10,81229.06,0,1
39,38558.51,82982.09,174999.30,81005.76,0,0
40,28754.33,118546.05,172795.67,78239.91,0,0
41,27892.92,84710.77,164470.71,77798.83,1,0
42,23640.93,96189.63,148001.11,71498.49,0,0
43,15505.73,127382.30,35534.17,69758.98,0,1
44,22177.74,154806.14,28334.72,65200.33,0,0
45,1000.23,124153.04,1903.93,64926.08,0,1
46,1315.46,115816.21,297114.46,49490.75,1,0
47,0.00,135426.92,0.00,42559.73,0,0
48,542.05,51743.15,0.00,35673.41,0,1
49,0.00,116983.80,45173.06,14681.40,0,0

In [10]:
dataset1

,R&D Spend,Administration,Marketing Spend,Profit,State_California,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,0,1
1,162597.70,151377.59,443898.53,191792.06,1,0,0
2,153441.51,101145.55,407934.54,191050.39,0,1,0
3,144372.41,118671.85,383199.62,182901.99,0,0,1
4,142107.34,91391.77,366168.42,166187.94,0,1,0
5,131876.90,99814.71,362861.36,156991.12,0,0,1
6,134615.46,147198.87,127716.82,156122.51,1,0,0
7,130298.13,145530.06,323876.68,155752.60,0,1,0
8,120542.52,148718.95,311613.29,152211.77,0,0,1
9,123334.88,108679.17,304981.62,149759.96,1,0,0
10,101913.08,110594.11,229160.95,146121.95,0,1,0
11,100671.96,91790.61,249744.55,144259.40,1,0,0
12,93863.75,127320.38,249839.44,141585.52,0,1,0
13,91992.39,135495.07,252664.93,134307.35,1,0,0
14,119943.24,156547.42,256512.92,132602.65,0,1,0
15,114523.61,122616.84,261776.23,129917.04,0,0,1
16,78013.11,121597.55,264346.06,126992.93,1,0,0
17,94657.16,145077.58,282574.31,125370.37,0,0,1
18,91749.16,114175.79,294919.57,124266.90,0,1,0
19,86419.70,153514.11,0.00,122776.86,0,0,1
20,76253.86,113867.30,298664.47,118474.03,1,0,0
21,78389.47,153773.43,299737.29,111313.02,0,0,1
22,73994.56,122782.75,303319.26,110352.25,0,1,0
23,67532.53,105751.03,304768.73,108733.99,0,1,0
24,77044.01,99281.34,140574.81,108552.04,0,0,1
25,64664.71,139553.16,137962.62,107404.34,1,0,0
26,75328.87,144135.98,134050.07,105733.54,0,1,0
27,72107.60,127864.55,353183.81,105008.31,0,0,1
28,66051.52,182645.56,118148.20,103282.38,0,1,0
29,65605.48,153032.06,107138.38,101004.64,0,0,1
30,61994.48,115641.28,91131.24,99937.59,0,1,0
31,61136.38,152701.92,88218.23,97483.56,0,0,1
32,63408.86,129219.61,46085.25,97427.84,1,0,0
33,55493.95,103057.49,214634.81,96778.92,0,1,0
34,46426.07,157693.92,210797.67,96712.80,1,0,0
35,46014.02,85047.44,205517.64,96479.51,0,0,1
36,28663.76,127056.21,201126.82,90708.19,0,1,0
37,44069.95,51283.14,197029.42,89949.14,1,0,0
38,20229.59,65947.93,185265.10,81229.06,0,0,1
39,38558.51,82982.09,174999.30,81005.76,1,0,0
40,28754.33,118546.05,172795.67,78239.91,1,0,0
41,27892.92,84710.77,164470.71,77798.83,0,1,0
42,23640.93,96189.63,148001.11,71498.49,1,0,0
43,15505.73,127382.30,35534.17,69758.98,0,0,1
44,22177.74,154806.14,28334.72,65200.33,1,0,0
45,1000.23,124153.04,1903.93,64926.08,0,0,1
46,1315.46,115816.21,297114.46,49490.75,0,1,0
47,0.00,135426.92,0.00,42559.73,1,0,0
48,542.05,51743.15,0.00,35673.41,0,0,1
49,0.00,116983.80,45173.06,14681.40,1,0,0

In [13]:
#to display columns, and we can use to copy paste field names
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [15]:
#spliting input and output varialbes,
#output variable is profit, rest all inputs
#assigning input varialbes to 'independent' variable 
independent=dataset[['R&D Spend', 'Administration', 'Marketing Spend', 
       'State_Florida', 'State_New York']]

In [16]:
independent

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0   165349.20       136897.80        471784.10              0               1
1   162597.70       151377.59        443898.53              0               0
2   153441.51       101145.55        407934.54              1               0
3   144372.41       118671.85        383199.62              0               1
4   142107.34        91391.77        366168.42              1               0
5   131876.90        99814.71        362861.36              0               1
6   134615.46       147198.87        127716.82              0               0
7   130298.13       145530.06        323876.68              1               0
8   120542.52       148718.95        311613.29              0               1
9   123334.88       108679.17        304981.62              0               0
10  101913.08       110594.11        229160.95              1               0
11  100671.96        91790.61        249744.55              0               0
12   93863.75       127320.38        249839.44              1               0
13   91992.39       135495.07        252664.93              0               0
14  119943.24       156547.42        256512.92              1               0
15  114523.61       122616.84        261776.23              0               1
16   78013.11       121597.55        264346.06              0               0
17   94657.16       145077.58        282574.31              0               1
18   91749.16       114175.79        294919.57              1               0
19   86419.70       153514.11             0.00              0               1
20   76253.86       113867.30        298664.47              0               0
21   78389.47       153773.43        299737.29              0               1
22   73994.56       122782.75        303319.26              1               0
23   67532.53       105751.03        304768.73              1               0
24   77044.01        99281.34        140574.81              0               1
25   64664.71       139553.16        137962.62              0               0
26   75328.87       144135.98        134050.07              1               0
27   72107.60       127864.55        353183.81              0               1
28   66051.52       182645.56        118148.20              1               0
29   65605.48       153032.06        107138.38              0               1
30   61994.48       115641.28         91131.24              1               0
31   61136.38       152701.92         88218.23              0               1
32   63408.86       129219.61         46085.25              0               0
33   55493.95       103057.49        214634.81              1               0
34   46426.07       157693.92        210797.67              0               0
35   46014.02        85047.44        205517.64              0               1
36   28663.76       127056.21        201126.82              1               0
37   44069.95        51283.14        197029.42              0               0
38   20229.59        65947.93        185265.10              0               1
39   38558.51        82982.09        174999.30              0               0
40   28754.33       118546.05        172795.67              0               0
41   27892.92        84710.77        164470.71              1               0
42   23640.93        96189.63        148001.11              0               0
43   15505.73       127382.30         35534.17              0               1
44   22177.74       154806.14         28334.72              0               0
45    1000.23       124153.04          1903.93              0               1
46    1315.46       115816.21        297114.46              1               0
47       0.00       135426.92             0.00              0               0
48     542.05        51743.15             0.00              0               1
49       0.00       116983.80         45173.06              0               0

In [17]:
#get output varialbe in 'dependent' variable
dependent=dataset[['Profit']]

In [18]:
dependent

       Profit
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   152211.77
9   149759.96
10  146121.95
11  144259.40
12  141585.52
13  134307.35
14  132602.65
15  129917.04
16  126992.93
17  125370.37
18  124266.90
19  122776.86
20  118474.03
21  111313.02
22  110352.25
23  108733.99
24  108552.04
25  107404.34
26  105733.54
27  105008.31
28  103282.38
29  101004.64
30   99937.59
31   97483.56
32   97427.84
33   96778.92
34   96712.80
35   96479.51
36   90708.19
37   89949.14
38   81229.06
39   81005.76
40   78239.91
41   77798.83
42   71498.49
43   69758.98
44   65200.33
45   64926.08
46   49490.75
47   42559.73
48   35673.41
49   14681.40

In [19]:
#now divide train set and test set
from sklearn.model_selection import train_test_split
#train 80%, test 20%
x_train,x_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.20, random_state=0)

In [28]:
#now create model using training set
from sklearn.svm import SVR
regressor=SVR(kernel="rbf")
regressor.fit(x_train,y_train)  #model created by this fit command

C:\Users\bills\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

SVR()

In [29]:
#to find the weight of model
weight=regressor.coef_
weight

AttributeError: coef_ is only available when using a linear kernel

In [31]:
#to know the bias value of model & to print it
bias=regressor.intercept_
bias

array([107983.13698394])

In [32]:
#start evaluating model
#to find the evaluation metrics on the input test data
y_pred=regressor.predict(x_test)

In [33]:
# to know r square metric - diff between actual o/p value of (x_test)-i.e y_test and predicted value of (x_test) - that is y_predicted
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [34]:
#printing r square ---> if nearly 1 , good model.  if near to 0, bad model
r_score

-0.1594737803854509

In [35]:
#to know how many data-points / support vectors the model has taken n created
regressor.n_support_

array([40])

In [ ]:
#40 support vector points it has taken n got created (model)

In [36]:
regressor.support_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [37]:
#since r square value is minus - not good model, so try standardisation after training-set, test set split

In [42]:
#now divide train set and test set
from sklearn.model_selection import train_test_split
#train 80%, test 20%
X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.20, random_state=0)

In [43]:
#just to know how X_train values are,
X_train

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
33   55493.95       103057.49        214634.81              1               0
35   46014.02        85047.44        205517.64              0               1
26   75328.87       144135.98        134050.07              1               0
34   46426.07       157693.92        210797.67              0               0
18   91749.16       114175.79        294919.57              1               0
7   130298.13       145530.06        323876.68              1               0
14  119943.24       156547.42        256512.92              1               0
45    1000.23       124153.04          1903.93              0               1
48     542.05        51743.15             0.00              0               1
29   65605.48       153032.06        107138.38              0               1
15  114523.61       122616.84        261776.23              0               1
30   61994.48       115641.28         91131.24              1               0
32   63408.86       129219.61         46085.25              0               0
16   78013.11       121597.55        264346.06              0               0
42   23640.93        96189.63        148001.11              0               0
20   76253.86       113867.30        298664.47              0               0
43   15505.73       127382.30         35534.17              0               1
8   120542.52       148718.95        311613.29              0               1
13   91992.39       135495.07        252664.93              0               0
25   64664.71       139553.16        137962.62              0               0
5   131876.90        99814.71        362861.36              0               1
17   94657.16       145077.58        282574.31              0               1
40   28754.33       118546.05        172795.67              0               0
49       0.00       116983.80         45173.06              0               0
1   162597.70       151377.59        443898.53              0               0
12   93863.75       127320.38        249839.44              1               0
37   44069.95        51283.14        197029.42              0               0
24   77044.01        99281.34        140574.81              0               1
6   134615.46       147198.87        127716.82              0               0
23   67532.53       105751.03        304768.73              1               0
36   28663.76       127056.21        201126.82              1               0
21   78389.47       153773.43        299737.29              0               1
19   86419.70       153514.11             0.00              0               1
9   123334.88       108679.17        304981.62              0               0
39   38558.51        82982.09        174999.30              0               0
46    1315.46       115816.21        297114.46              1               0
3   144372.41       118671.85        383199.62              0               1
0   165349.20       136897.80        471784.10              0               1
47       0.00       135426.92             0.00              0               0
44   22177.74       154806.14         28334.72              0               0

In [44]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [45]:
#now standardisation has happened using above commands
X_train

array([[-0.35006454, -0.78547109,  0.1011968 ,  1.73205081, -0.73379939],
       [-0.55530319, -1.48117426,  0.02734979, -0.57735027,  1.36277029],
       [ 0.07935762,  0.80133381, -0.55152132,  1.73205081, -0.73379939],
       [-0.54638238,  1.32505817,  0.07011684, -0.57735027, -0.73379939],
       [ 0.43485371, -0.35598663,  0.75148516,  1.73205081, -0.73379939],
       [ 1.26943143,  0.85518519,  0.98603118,  1.73205081, -0.73379939],
       [ 1.04525007,  1.28077047,  0.4404    ,  1.73205081, -0.73379939],
       [-1.529843  ,  0.02942065, -1.6218751 , -0.57735027,  1.36277029],
       [-1.53976251, -2.76767264, -1.6372965 , -0.57735027,  1.36277029],
       [-0.13115188,  1.14497701, -0.76949991, -0.57735027,  1.36277029],
       [ 0.92791613, -0.02992062,  0.48303162, -0.57735027,  1.36277029],
       [-0.20932933, -0.2993768 , -0.89915412,  1.73205081, -0.73379939],
       [-0.17870828,  0.2251352 , -1.26401642, -0.57735027, -0.73379939],
       [ 0.1374709 , -0.06929437,  0.50384666, -0.57735027, -0.73379939],
       [-1.03967624, -1.05076697, -0.43852106, -0.57735027, -0.73379939],
       [ 0.09938348, -0.36790317,  0.781818  , -0.57735027, -0.73379939],
       [-1.21580174,  0.15416247, -1.34947778, -0.57735027,  1.36277029],
       [ 1.05822437,  0.97836757,  0.88670051, -0.57735027,  1.36277029],
       [ 0.4401196 ,  0.46754749,  0.40923215, -0.57735027, -0.73379939],
       [-0.15151937,  0.62430586, -0.51983056, -0.57735027, -0.73379939],
       [ 1.30361149, -0.91073517,  1.30179825, -0.57735027,  1.36277029],
       [ 0.49781135,  0.83770651,  0.65149135, -0.57735027,  1.36277029],
       [-0.92897212, -0.18716957, -0.23769075, -0.57735027, -0.73379939],
       [-1.55149779, -0.24751712, -1.27140496, -0.57735027, -0.73379939],
       [ 1.96871085,  1.08106713,  1.95818096, -0.57735027, -0.73379939],
       [ 0.48063418,  0.15177059,  0.38634632,  1.73205081, -0.73379939],
       [-0.59739193, -2.78544219, -0.04140287, -0.57735027, -0.73379939],
       [ 0.11649007, -0.93133851, -0.49867241, -0.57735027,  1.36277029],
       [ 1.36290079,  0.91964899, -0.60281921, -0.57735027, -0.73379939],
       [-0.08943162, -0.68142339,  0.83126112,  1.73205081, -0.73379939],
       [-0.93093295,  0.14156607, -0.00821485,  1.73205081, -0.73379939],
       [ 0.14561902,  1.1736151 ,  0.7905076 , -0.57735027,  1.36277029],
       [ 0.31947194,  1.16359793, -1.6372965 , -0.57735027,  1.36277029],
       [ 1.11867842, -0.56831342,  0.83298548, -0.57735027, -0.73379939],
       [-0.71671353, -1.56095586, -0.21984184, -0.57735027, -0.73379939],
       [-1.52301833, -0.29261949,  0.76926327,  1.73205081, -0.73379939],
       [ 1.57413686, -0.18231009,  1.46653355, -0.57735027,  1.36277029],
       [ 2.02828029,  0.52173299,  2.18404776, -0.57735027,  1.36277029],
       [-1.55149779,  0.46491495, -1.6372965 , -0.57735027, -0.73379939],
       [-1.07135402,  1.21350725, -1.40779169, -0.57735027, -0.73379939]])

In [46]:
#now again create model using training set - after standardisation
from sklearn.svm import SVR
regressor=SVR(kernel="rbf")
regressor.fit(X_train,y_train)  #model created by this fit command

C:\Users\bills\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

SVR()

In [48]:
#start evaluating model
#to find the evaluation metrics on the input test data
y_pred=regressor.predict(X_test)

In [49]:
# to know r square metric - diff between actual o/p value of (x_test)-i.e y_test and predicted value of (x_test) - that is y_predicted
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [50]:
#printing r square ---> if nearly 1 , good model.  if near to 0, bad model
r_score

-0.15975844267299522

In [ ]:
#the above answer says - no use of standardisation

In [68]:
#now try to improve model with including c value
#now again create model using training set - after standardisation
from sklearn.svm import SVR
regressor=SVR(kernel="rbf", C=2000) #c can be given from 0.01 to 1000...)
regressor.fit(X_train,y_train)  #model created by this fit command

C:\Users\bills\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

SVR(C=2000)

In [69]:
#start evaluating model
#to find the evaluation metrics on the input test data
y_pred=regressor.predict(X_test)

In [70]:
# to know r square metric - diff between actual o/p value of (x_test)-i.e y_test and predicted value of (x_test) - that is y_predicted
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [72]:
#printing r square ---> if nearly 1 , good model.  if near to 0, bad model
r_score

0.003968746501458842

In [82]:
#lets try now linear in standardised data
X_train

array([[-0.35006454, -0.78547109,  0.1011968 ,  1.73205081, -0.73379939],
       [-0.55530319, -1.48117426,  0.02734979, -0.57735027,  1.36277029],
       [ 0.07935762,  0.80133381, -0.55152132,  1.73205081, -0.73379939],
       [-0.54638238,  1.32505817,  0.07011684, -0.57735027, -0.73379939],
       [ 0.43485371, -0.35598663,  0.75148516,  1.73205081, -0.73379939],
       [ 1.26943143,  0.85518519,  0.98603118,  1.73205081, -0.73379939],
       [ 1.04525007,  1.28077047,  0.4404    ,  1.73205081, -0.73379939],
       [-1.529843  ,  0.02942065, -1.6218751 , -0.57735027,  1.36277029],
       [-1.53976251, -2.76767264, -1.6372965 , -0.57735027,  1.36277029],
       [-0.13115188,  1.14497701, -0.76949991, -0.57735027,  1.36277029],
       [ 0.92791613, -0.02992062,  0.48303162, -0.57735027,  1.36277029],
       [-0.20932933, -0.2993768 , -0.89915412,  1.73205081, -0.73379939],
       [-0.17870828,  0.2251352 , -1.26401642, -0.57735027, -0.73379939],
       [ 0.1374709 , -0.06929437,  0.50384666, -0.57735027, -0.73379939],
       [-1.03967624, -1.05076697, -0.43852106, -0.57735027, -0.73379939],
       [ 0.09938348, -0.36790317,  0.781818  , -0.57735027, -0.73379939],
       [-1.21580174,  0.15416247, -1.34947778, -0.57735027,  1.36277029],
       [ 1.05822437,  0.97836757,  0.88670051, -0.57735027,  1.36277029],
       [ 0.4401196 ,  0.46754749,  0.40923215, -0.57735027, -0.73379939],
       [-0.15151937,  0.62430586, -0.51983056, -0.57735027, -0.73379939],
       [ 1.30361149, -0.91073517,  1.30179825, -0.57735027,  1.36277029],
       [ 0.49781135,  0.83770651,  0.65149135, -0.57735027,  1.36277029],
       [-0.92897212, -0.18716957, -0.23769075, -0.57735027, -0.73379939],
       [-1.55149779, -0.24751712, -1.27140496, -0.57735027, -0.73379939],
       [ 1.96871085,  1.08106713,  1.95818096, -0.57735027, -0.73379939],
       [ 0.48063418,  0.15177059,  0.38634632,  1.73205081, -0.73379939],
       [-0.59739193, -2.78544219, -0.04140287, -0.57735027, -0.73379939],
       [ 0.11649007, -0.93133851, -0.49867241, -0.57735027,  1.36277029],
       [ 1.36290079,  0.91964899, -0.60281921, -0.57735027, -0.73379939],
       [-0.08943162, -0.68142339,  0.83126112,  1.73205081, -0.73379939],
       [-0.93093295,  0.14156607, -0.00821485,  1.73205081, -0.73379939],
       [ 0.14561902,  1.1736151 ,  0.7905076 , -0.57735027,  1.36277029],
       [ 0.31947194,  1.16359793, -1.6372965 , -0.57735027,  1.36277029],
       [ 1.11867842, -0.56831342,  0.83298548, -0.57735027, -0.73379939],
       [-0.71671353, -1.56095586, -0.21984184, -0.57735027, -0.73379939],
       [-1.52301833, -0.29261949,  0.76926327,  1.73205081, -0.73379939],
       [ 1.57413686, -0.18231009,  1.46653355, -0.57735027,  1.36277029],
       [ 2.02828029,  0.52173299,  2.18404776, -0.57735027,  1.36277029],
       [-1.55149779,  0.46491495, -1.6372965 , -0.57735027, -0.73379939],
       [-1.07135402,  1.21350725, -1.40779169, -0.57735027, -0.73379939]])

In [78]:
#now try to improve model with including c value
#now again create model using training set - after standardisation
from sklearn.svm import SVR
regressor=SVR(kernel="linear" ) #c can be given from 0.01 to 1000...)
regressor.fit(X_train,y_train)  #model created by this fit command

C:\Users\bills\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

SVR(kernel='linear')

In [79]:
#start evaluating model
#to find the evaluation metrics on the input test data
y_pred=regressor.predict(X_test)

In [80]:
# to know r square metric - diff between actual o/p value of (x_test)-i.e y_test and predicted value of (x_test) - that is y_predicted
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [81]:
#printing r square ---> if nearly 1 , good model.  if near to 0, bad model
r_score

-0.15724238554658765

In [83]:
#try again wit out standardisation
#now divide train set and test set
from sklearn.model_selection import train_test_split
#train 80%, test 20%
x_train,x_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.20, random_state=0)

In [84]:
x_train

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
33   55493.95       103057.49        214634.81              1               0
35   46014.02        85047.44        205517.64              0               1
26   75328.87       144135.98        134050.07              1               0
34   46426.07       157693.92        210797.67              0               0
18   91749.16       114175.79        294919.57              1               0
7   130298.13       145530.06        323876.68              1               0
14  119943.24       156547.42        256512.92              1               0
45    1000.23       124153.04          1903.93              0               1
48     542.05        51743.15             0.00              0               1
29   65605.48       153032.06        107138.38              0               1
15  114523.61       122616.84        261776.23              0               1
30   61994.48       115641.28         91131.24              1               0
32   63408.86       129219.61         46085.25              0               0
16   78013.11       121597.55        264346.06              0               0
42   23640.93        96189.63        148001.11              0               0
20   76253.86       113867.30        298664.47              0               0
43   15505.73       127382.30         35534.17              0               1
8   120542.52       148718.95        311613.29              0               1
13   91992.39       135495.07        252664.93              0               0
25   64664.71       139553.16        137962.62              0               0
5   131876.90        99814.71        362861.36              0               1
17   94657.16       145077.58        282574.31              0               1
40   28754.33       118546.05        172795.67              0               0
49       0.00       116983.80         45173.06              0               0
1   162597.70       151377.59        443898.53              0               0
12   93863.75       127320.38        249839.44              1               0
37   44069.95        51283.14        197029.42              0               0
24   77044.01        99281.34        140574.81              0               1
6   134615.46       147198.87        127716.82              0               0
23   67532.53       105751.03        304768.73              1               0
36   28663.76       127056.21        201126.82              1               0
21   78389.47       153773.43        299737.29              0               1
19   86419.70       153514.11             0.00              0               1
9   123334.88       108679.17        304981.62              0               0
39   38558.51        82982.09        174999.30              0               0
46    1315.46       115816.21        297114.46              1               0
3   144372.41       118671.85        383199.62              0               1
0   165349.20       136897.80        471784.10              0               1
47       0.00       135426.92             0.00              0               0
44   22177.74       154806.14         28334.72              0               0

In [89]:
#now try to improve model with including c value
#now again create model using training set - after standardisation
from sklearn.svm import SVR
regressor=SVR(kernel="linear" ) #c can be given from 0.01 to 1000...)
regressor.fit(x_train,y_train)  #model created by this fit command

C:\Users\bills\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

SVR(kernel='linear')

In [90]:
#start evaluating model
#to find the evaluation metrics on the input test data
y_pred=regressor.predict(x_test)

In [91]:
# to know r square metric - diff between actual o/p value of (x_test)-i.e y_test and predicted value of (x_test) - that is y_predicted
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [92]:
#printing r square ---> if nearly 1 , good model.  if near to 0, bad model
r_score

0.8742574194622766