In [1]:
#Decision Tree (DT) Hands on - regression - insurance-charges pred.
#import libraries
import pandas as pd

import numpy as np
import matplotlib.pyplot as plt

In [2]:
#reading the data file
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
#just to display dataset
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#understand two set of variables X_train and x_train (case sensitives - holding two diff sets)

In [5]:
#categorical data is present - nominal (by name - state name)
#expanding columns - as machine understanding - one hot encoding
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [7]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [8]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

C:\Users\bills\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['mse','mae','friedman_mse'],
'max_features': ['auto','sqrt','log2'],
'splitter':['best','random']}
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [10]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test)

In [11]:
# print classification report
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': 'auto', 'splitter': 'best'}: 0.6904243467177256

In [12]:
table=pd.DataFrame.from_dict(re)

In [13]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005984,1.545018e-03,0.001995,6.306004e-04,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",0.690632,0.497759,0.721831,0.612933,0.645341,0.633699,0.077531,5
1,0.003990,1.871244e-06,0.001795,3.990417e-04,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",0.524924,0.653453,0.691004,0.577024,0.608019,0.610885,0.057923,8
2,0.004888,6.601934e-04,0.001996,6.313558e-04,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.647417,0.505521,0.469885,0.614178,0.484937,0.544388,0.072224,17
3,0.004092,6.635043e-04,0.001995,2.611745e-07,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.516141,0.581867,0.658994,0.538183,0.523230,0.563683,0.052843,13
4,0.003790,3.988745e-04,0.001995,5.135693e-07,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",0.667565,0.415222,0.676098,0.655172,0.640306,0.610873,0.098566,9
5,0.002992,3.504023e-07,0.001795,3.988982e-04,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",0.629875,0.607504,0.684973,0.407375,0.482142,0.562374,0.102064,14
6,0.017753,7.458965e-04,0.001996,1.293627e-06,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",0.632253,0.558421,0.704305,0.632268,0.640917,0.633633,0.046278,6
7,0.014273,5.068431e-04,0.001995,3.814697e-07,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",0.720120,0.617961,0.714498,0.517785,0.631152,0.640303,0.074120,3
8,0.012072,1.272675e-03,0.002194,3.987074e-04,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.620273,0.578849,0.647529,0.539265,0.605685,0.598320,0.036944,11
9,0.008577,2.491347e-03,0.002395,4.895705e-04,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.641289,0.674174,0.512521,0.293262,-0.141318,0.395985,0.300130,18
10,0.011967,1.410807e-03,0.002394,4.884804e-04,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",0.501323,0.515619,0.625523,0.571387,0.539324,0.550635,0.044328,16
11,0.008976,6.306757e-04,0.001995,1.907349e-07,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",0.621148,0.684027,0.452532,0.592481,0.604739,0.590986,0.076062,12
12,0.004787,3.985410e-04,0.001994,6.306003e-04,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.685532,0.484688,0.770414,0.612015,0.670259,0.644581,0.094654,1
13,0.003790,3.987791e-04,0.001596,4.882468e-04,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.634786,0.650231,0.670057,0.647984,0.619677,0.644547,0.016785,2
14,0.003590,4.887141e-04,0.001596,4.884999e-04,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.617860,0.514426,0.684749,0.731175,0.629640,0.635570,0.072916,4
15,0.003191,3.990890e-04,0.001596,4.884804e-04,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.546234,0.658752,0.540844,0.549534,0.460542,0.551181,0.063120,15
16,0.003391,4.883831e-04,0.001596,4.885583e-04,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.709831,0.633355,0.680412,0.469937,0.648231,0.628353,0.083504,7
17,0.003192,3.990419e-04,0.001596,4.882474e-04,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.597902,0.633900,0.628093,0.539025,0.609041,0.601592,0.033852,10

In [14]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:48
BMI:30
Children:2
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [16]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[9620.3307]

#lets now try in normal decision tree - with same parameters given as best by the above gridsearch

In [23]:
#now create model using training set
from sklearn.tree import DecisionTreeRegressor
#regressor=DecisionTreeRegressor() #1st -method - default 95%
#regressor=DecisionTreeRegressor(criterion='friedman_mse',splitter='best') #2nd method-97%
regressor=DecisionTreeRegressor(criterion='friedman_mse', splitter='best',max_features='auto',) #3rd method-82%%
regressor.fit(X_train,y_train)  #model created by this fit command

DecisionTreeRegressor(criterion='friedman_mse', max_features='auto')

In [25]:
#start evaluating model
#to find the evaluation metrics on the input test data
y_pred=regressor.predict(X_test)

In [26]:
# to know r square metric - diff between actual o/p value of (x_test)-i.e y_test and predicted value of (x_test) - that is y_predicted
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [27]:
#printing r square ---> if nearly 1 , good model.  if near to 0, bad model
r_score

0.7002186206088747