In [1]:
#Random Forest (RF) Hands on - regression - insurance_charges prediction
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
#just to display dataset
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#understand two set of variables X_train and x_train (case sensitives - holding two diff sets)

In [5]:
#categorical data is present - nominal (by name - state name)
#expanding columns - as machine understanding - one hot encoding
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [7]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [8]:
#to display columns, and we can use to copy paste field names
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [9]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [10]:
#split into training set and test
from sklearn.model_selection import train_test_split

#X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

C:\Users\bills\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [11]:
from sklearn.ensemble import RandomForestRegressor

In [12]:
from sklearn.model_selection import GridSearchCV
#from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['mse','mae'],
'max_features': ['auto','sqrt','log2'],
'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
# fitting the model for grid search
#grid.fit(X_train, y_train)
grid.fit(indep, dep)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [14]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_

print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'mse', 'max_features': 'log2', 'n_estimators': 100}:

In [15]:
table=pd.DataFrame.from_dict(re)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.032821,0.000577,0.003790,0.000399,mse,auto,10,"{'criterion': 'mse', 'max_features': 'auto', '...",0.824168,0.749903,0.853647,0.800982,0.816528,0.809046,0.034167,12
1,0.294956,0.002475,0.014960,0.000631,mse,auto,100,"{'criterion': 'mse', 'max_features': 'auto', '...",0.847170,0.773516,0.855965,0.818937,0.835349,0.826187,0.029113,5
2,0.026439,0.000550,0.003294,0.000400,mse,sqrt,10,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.849503,0.774339,0.823302,0.821851,0.819820,0.817763,0.024268,8
3,0.230426,0.000895,0.014065,0.000204,mse,sqrt,100,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.861031,0.775439,0.862852,0.829935,0.838234,0.833498,0.031704,3
4,0.026729,0.001467,0.003591,0.000489,mse,log2,10,"{'criterion': 'mse', 'max_features': 'log2', '...",0.847721,0.764724,0.841419,0.815862,0.817124,0.817370,0.029235,9
5,0.235014,0.000919,0.014265,0.001659,mse,log2,100,"{'criterion': 'mse', 'max_features': 'log2', '...",0.860157,0.781545,0.864045,0.830670,0.843883,0.836060,0.029752,1
6,0.162283,0.002986,0.003193,0.000398,mae,auto,10,"{'criterion': 'mae', 'max_features': 'auto', '...",0.834310,0.750990,0.849024,0.805844,0.815817,0.811197,0.033585,11
7,1.408843,0.021503,0.008383,0.000482,mae,auto,100,"{'criterion': 'mae', 'max_features': 'auto', '...",0.839666,0.774449,0.856636,0.821874,0.837923,0.826110,0.028078,6
8,0.099049,0.002309,0.003191,0.000399,mae,sqrt,10,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.839218,0.761874,0.872846,0.818798,0.807484,0.820044,0.036603,7
9,0.925949,0.026342,0.011272,0.001600,mae,sqrt,100,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.855657,0.776683,0.852381,0.827468,0.843886,0.831215,0.028961,4
10,0.100844,0.003064,0.003191,0.000399,mae,log2,10,"{'criterion': 'mae', 'max_features': 'log2', '...",0.852234,0.761325,0.809742,0.814660,0.827709,0.813134,0.029797,10
11,0.922861,0.009293,0.009967,0.001548,mae,log2,100,"{'criterion': 'mae', 'max_features': 'log2', '...",0.857093,0.779845,0.859418,0.827426,0.850015,0.834760,0.029695,2

In [17]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:48
BMI:30
Children:2
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [18]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[10569.5594648]