In [1]:
#Random Forest (RF) Hands on - regression - insurance_charges prediction
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
#just to display dataset
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#understand two set of variables X_train and x_train (case sensitives - holding two diff sets)

In [5]:
#categorical data is present - nominal (by name - state name)
#expanding columns - as machine understanding - one hot encoding
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [7]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [8]:
#to display columns, and we can use to copy paste field names
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [9]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [10]:
#split into training set and test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

C:\Users\bills\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
from sklearn.ensemble import RandomForestRegressor

In [13]:
from sklearn.model_selection import GridSearchCV
#from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['mse','mae'],
'max_features': ['auto','sqrt','log2'],
'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [14]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test)
# print classification report
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'mse', 'max_features': 'sqrt', 'n_estimators': 100}: 0.8723386581549056

In [15]:
table=pd.DataFrame.from_dict(re)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.024734,0.000399,0.002793,3.988267e-04,mse,auto,10,"{'criterion': 'mse', 'max_features': 'auto', '...",0.796932,0.738783,0.815900,0.783454,0.753794,0.777773,0.028101,8
1,0.232814,0.003718,0.011273,5.954275e-04,mse,auto,100,"{'criterion': 'mse', 'max_features': 'auto', '...",0.804403,0.746832,0.829314,0.809037,0.766230,0.791163,0.030123,5
2,0.021150,0.001861,0.001995,4.101908e-07,mse,sqrt,10,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.793655,0.746610,0.815541,0.776768,0.737010,0.773917,0.029114,11
3,0.193312,0.005442,0.010977,3.146697e-04,mse,sqrt,100,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.811075,0.772201,0.838886,0.831754,0.765564,0.803896,0.030086,1
4,0.019547,0.001197,0.002194,3.988507e-04,mse,log2,10,"{'criterion': 'mse', 'max_features': 'log2', '...",0.763767,0.748981,0.820396,0.811503,0.729385,0.774806,0.035431,9
5,0.190920,0.010491,0.010174,3.985425e-04,mse,log2,100,"{'criterion': 'mse', 'max_features': 'log2', '...",0.806986,0.769208,0.829053,0.836785,0.760198,0.800446,0.030911,2
6,0.096257,0.001893,0.001596,4.890064e-04,mae,auto,10,"{'criterion': 'mae', 'max_features': 'auto', '...",0.760892,0.753156,0.804994,0.772239,0.739719,0.766200,0.022095,12
7,0.818320,0.008754,0.006782,3.996850e-04,mae,auto,100,"{'criterion': 'mae', 'max_features': 'auto', '...",0.786003,0.768110,0.815826,0.802219,0.754750,0.785382,0.022124,6
8,0.058359,0.002274,0.001396,4.884220e-04,mae,sqrt,10,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.792028,0.720787,0.834333,0.792273,0.730733,0.774031,0.042433,10
9,0.551205,0.009945,0.009575,1.353169e-03,mae,sqrt,100,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.801966,0.769312,0.839980,0.821239,0.766916,0.799883,0.028599,3
10,0.057845,0.001262,0.001796,3.993758e-04,mae,log2,10,"{'criterion': 'mae', 'max_features': 'log2', '...",0.803027,0.762386,0.824664,0.783329,0.751979,0.785077,0.026468,7
11,0.533745,0.013936,0.008480,1.670698e-03,mae,log2,100,"{'criterion': 'mae', 'max_features': 'log2', '...",0.804319,0.761017,0.843604,0.826617,0.759928,0.799097,0.033911,4

In [17]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:48
BMI:30
Children:2
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [18]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[14104.8219583]